/**
 * Reactive UI state fed from SpacetimeDB row events.
 *
 * # Why project here?
 *
 * The generated SDK rows use camelCase field names and numeric domain
 * tags (matching the module schema). The rest of the UI was designed
 * around string ids and snake_case (matching an older REST envelope).
 * Translating at the edge — here — keeps components unaware of the
 * transport and keeps the SDK bindings unmodified (they are
 * regenerated by `spacetime generate`).
 *
 * # Bounds
 *
 * Each projected list has a fixed maximum size. The module *already*
 * caps the rings on the server, but we apply a second cap here so:
 *   * a browser that connects to a module with a larger ring than we
 *     expect still stays responsive; and
 *   * subscription queries like `ORDER BY ordinal DESC LIMIT N` have a
 *     canonical `N` to reference.
 *
 * The `apply*` and `remove*` helpers are the only permitted mutation
 * path — `connection.svelte.ts` calls them from SDK row callbacks.
 */

import type {
  CausalEdge,
  DomainInsight,
  Event,
  EventNarrative,
  Signal,
  WorldStateRow,
} from "./stdb/types";
import { domainIdFromTag } from "./domain";
import { notifyError } from "./notify/notify";
import { NOTIFY_CODES } from "./notify/notify-codes";
import {
  MAX_CAUSAL_EDGES,
  MAX_EVENT_NARRATIVES,
  MAX_EVENTS,
  MAX_SEVERITY_HISTORY,
  MAX_SIGNALS,
} from "./data-limits";
import { bumpDomainsRevision } from "./dashboard-revision.svelte";
import type {
  ConnectionState,
  UiCausalEdge,
  UiDomainInsight,
  UiEvent,
  UiEventNarrative,
  UiPredictedDisruption,
  UiSignal,
  UiWorldState,
} from "./types";

export {
  MAX_CAUSAL_EDGES,
  MAX_EVENT_NARRATIVES,
  MAX_EVENTS,
  MAX_SEVERITY_HISTORY,
  MAX_SIGNALS,
} from "./data-limits";

/**
 * Singleton dashboard state. Exposed as a rune-backed object so
 * components deep-read fields reactively without bespoke store
 * plumbing.
 */
export const dashboard = $state({
  events: [] as UiEvent[],
  recentSignals: [] as UiSignal[],
  domainState: {} as Record<string, UiWorldState>,
  domainSeverityHistory: {} as Record<string, number[]>,
  recentCausalEdges: [] as UiCausalEdge[],
  domainInsights: {} as Record<string, UiDomainInsight>,
  /**
   * Keyed by `event_id` (string). Sparse: the server only writes
   * narratives above a severity threshold, so most events will have no
   * entry. Consumers should always default to "no narrative available".
   */
  eventNarratives: {} as Record<string, UiEventNarrative>,
  selectedDomain: null as string | null,
  connection: "connecting" as ConnectionState,
  /**
   * Last SpacetimeDB error (connect, subscription, or manual reconnect
   * hint). Cleared on successful subscription setup.
   */
  connectionLastError: null as string | null,
  /** `demo` = synthetic `demo-seed` data; `live` = SpacetimeDB projection. */
  dataMode: "live" as "live" | "demo",
});

export function setConnection(next: ConnectionState): void {
  dashboard.connection = next;
}

export function setConnectionLastError(
  message: string | null,
): void {
  dashboard.connectionLastError = message;
}

export function setSelectedDomain(next: string | null): void {
  dashboard.selectedDomain = next;
}

export function matchesSelectedDomain(candidate: string): boolean {
  const selected = dashboard.selectedDomain;
  return selected === null || selected === candidate;
}

/** All domains the UI is currently tracking, in stable alphabetical order. */
export function activeDomains(): UiWorldState[] {
  return Object.values(dashboard.domainState).sort((a, b) =>
    a.domain.localeCompare(b.domain),
  );
}

// ---------------------------------------------------------------------------
// Row projections — SDK shape → UI shape
// ---------------------------------------------------------------------------

function projectLocation(
  loc: Event["location"],
): { lat: number; lon: number } | null {
  if (loc == null) return null;
  if (typeof loc === "object" && "lat" in loc && "lon" in loc) {
    return {
      lat: (loc as { lat: number }).lat,
      lon: (loc as { lon: number }).lon,
    };
  }
  return null;
}

/** Shallow parse of ingest canonical payload (schema_version 1). */
function readCanonicalPayload(json: string): {
  source?: string;
  icao24?: string;
  callsign?: string;
  velocity_mps?: number;
  true_track_deg?: number;
  baro_altitude_m?: number;
  on_ground?: boolean;
} {
  if (!json) return {};
  try {
    const p = JSON.parse(json) as Record<string, unknown>;
    const source =
      typeof p.src === "string"
        ? p.src
        : typeof p.source === "string"
          ? p.source
          : undefined;
    return {
      source,
      icao24: typeof p.icao24 === "string" ? p.icao24 : undefined,
      callsign:
        typeof p.callsign === "string" ? p.callsign.trim() : undefined,
      velocity_mps:
        typeof p.velocity_mps === "number" ? p.velocity_mps : undefined,
      true_track_deg:
        typeof p.true_track_deg === "number" ? p.true_track_deg : undefined,
      baro_altitude_m:
        typeof p.baro_altitude_m === "number" ? p.baro_altitude_m : undefined,
      on_ground: typeof p.on_ground === "boolean" ? p.on_ground : undefined,
    };
  } catch {
    return {};
  }
}

function projectEvent(row: Event): UiEvent {
  const canon = readCanonicalPayload(row.payloadJson);
  return {
    id: String(row.id),
    ordinal: Number(row.ordinal),
    timestamp: row.timestamp.toISOString(),
    domain: domainIdFromTag(row.domain),
    severity_score: row.severityScore,
    location: projectLocation(row.location),
    feedSource: canon.source,
    icao24: canon.icao24,
    callsign: canon.callsign,
    velocity_mps: canon.velocity_mps,
    true_track_deg: canon.true_track_deg,
    baro_altitude_m: canon.baro_altitude_m,
    on_ground: canon.on_ground,
  };
}

function projectSignal(row: Signal): UiSignal {
  return {
    id: String(row.id),
    event_id: String(row.eventId),
    domain: domainIdFromTag(row.domain),
    score: row.score,
    reason: row.reason,
  };
}

function projectCausalEdge(row: CausalEdge): UiCausalEdge {
  return {
    id: String(row.id),
    source_event_id: String(row.sourceEventId),
    target_event_id: String(row.targetEventId),
    influence_score: row.influenceScore,
    decay_rate: row.decayRate,
  };
}

function projectWorldState(row: WorldStateRow): UiWorldState {
  return {
    domain: domainIdFromTag(row.domain),
    event_count: Number(row.eventCount),
    avg_severity: row.avgSeverity,
    risk_index: row.riskIndex,
  };
}

function projectEventNarrative(row: EventNarrative): UiEventNarrative {
  return {
    event_id: String(row.eventId),
    headline: row.headline,
    summary: row.summary,
    inference: row.inference,
    predicted_disruption: parseDisruptions(row.predictedDisruptionJson),
    updated_at: row.updatedAt.toISOString(),
  };
}

/**
 * The module writes `predicted_disruption_json` as a JSON array of
 * `{entity, severity, note}`. We parse defensively: any malformed row
 * drops back to an empty list rather than crashing the view. This
 * preserves the "graceful fallback" contract for the Event Detail
 * view when bindings, schema, or data race each other during a deploy.
 */
function parseDisruptions(raw: string): UiPredictedDisruption[] {
  if (raw === "") return [];
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return [];
    const out: UiPredictedDisruption[] = [];
    for (const item of parsed) {
      if (
        item !== null &&
        typeof item === "object" &&
        "entity" in item &&
        "severity" in item &&
        "note" in item &&
        typeof (item as { entity: unknown }).entity === "string" &&
        typeof (item as { severity: unknown }).severity === "string" &&
        typeof (item as { note: unknown }).note === "string"
      ) {
        out.push({
          entity: (item as { entity: string }).entity,
          severity: (item as { severity: string }).severity,
          note: (item as { note: string }).note,
        });
      }
    }
    return out;
  } catch {
    return [];
  }
}

function projectDomainInsight(row: DomainInsight): UiDomainInsight {
  return {
    domain: domainIdFromTag(row.domain),
    trend: row.trend,
    anomaly_count_recent: row.anomalyCountRecent,
    dominant_source: row.dominantSource || null,
    source_link: row.sourceLink || null,
    narrative: row.narrative,
    updated_at: row.updatedAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Batched mutations (hydrate / bulk STDB apply)
// ---------------------------------------------------------------------------

let batchDepth = 0;
let batchEvents: UiEvent[] | null = null;
let batchSignals: UiSignal[] | null = null;
let batchCausalEdges: UiCausalEdge[] | null = null;
let batchNarratives: Record<string, UiEventNarrative> | null = null;
const batchSeverityEvents: UiEvent[] = [];

/** Suppress per-row reactive fan-out while hydrating or replaying many rows. */
export function beginDashboardBatch(): void {
  batchDepth += 1;
  if (batchDepth === 1) {
    batchEvents = [];
    batchSignals = [];
    batchCausalEdges = [];
    batchNarratives = {};
    batchSeverityEvents.length = 0;
  }
}

/** Commit batched buffers in one assignment + trim. */
export function endDashboardBatch(): void {
  if (batchDepth === 0) return;
  batchDepth -= 1;
  if (batchDepth > 0) return;

  if (batchEvents !== null) {
    dashboard.events = batchEvents;
    batchEvents = null;
  }
  if (batchSignals !== null) {
    dashboard.recentSignals = batchSignals;
    batchSignals = null;
  }
  if (batchCausalEdges !== null) {
    dashboard.recentCausalEdges = batchCausalEdges;
    batchCausalEdges = null;
  }
  if (batchNarratives !== null) {
    evictOldestNarratives(batchNarratives, MAX_EVENT_NARRATIVES);
    dashboard.eventNarratives = batchNarratives;
    batchNarratives = null;
  }
  flushPendingSeverityUpdates();
  eventIdToIndex.clear();
}

const eventIdToIndex = new Map<string, number>();

/** Live STDB rows buffer here until `flushPendingDashboardPatches` (one reactive commit/frame). */
const pendingEvents = new Map<string, UiEvent>();
const pendingSignals = new Map<string, UiSignal>();
const pendingCausalEdges = new Map<string, UiCausalEdge>();
const pendingWorldState: Record<string, UiWorldState> = {};
const pendingDomainInsights: Record<string, UiDomainInsight> = {};
const pendingEventDeletes = new Set<string>();
const pendingSignalDeletes = new Set<string>();
const pendingCausalDeletes = new Set<string>();

/** Merge pending patches then trim — called from `sortAndTrimDashboardBuffers`. */
export function flushPendingDashboardPatches(): void {
  let domainsDirty = false;

  if (pendingEventDeletes.size > 0) {
    dashboard.events = dashboard.events.filter(
      (e) => !pendingEventDeletes.has(e.id),
    );
    pendingEventDeletes.clear();
    eventIdToIndex.clear();
  }

  if (pendingEvents.size > 0) {
    const merged = new Map<string, UiEvent>();
    for (const e of dashboard.events) merged.set(e.id, e);
    for (const e of pendingEvents.values()) merged.set(e.id, e);
    pendingEvents.clear();
    dashboard.events = [...merged.values()];
    eventIdToIndex.clear();
  }

  if (pendingSignalDeletes.size > 0) {
    dashboard.recentSignals = dashboard.recentSignals.filter(
      (s) => !pendingSignalDeletes.has(s.id),
    );
    pendingSignalDeletes.clear();
  }

  if (pendingSignals.size > 0) {
    const merged = new Map<string, UiSignal>();
    for (const s of dashboard.recentSignals) merged.set(s.id, s);
    for (const s of pendingSignals.values()) merged.set(s.id, s);
    pendingSignals.clear();
    dashboard.recentSignals = [...merged.values()];
  }

  if (pendingCausalDeletes.size > 0) {
    dashboard.recentCausalEdges = dashboard.recentCausalEdges.filter(
      (e) => !pendingCausalDeletes.has(e.id),
    );
    pendingCausalDeletes.clear();
  }

  if (pendingCausalEdges.size > 0) {
    const merged = new Map<string, UiCausalEdge>();
    for (const e of dashboard.recentCausalEdges) merged.set(e.id, e);
    for (const e of pendingCausalEdges.values()) merged.set(e.id, e);
    pendingCausalEdges.clear();
    dashboard.recentCausalEdges = [...merged.values()];
  }

  if (Object.keys(pendingWorldState).length > 0) {
    dashboard.domainState = { ...dashboard.domainState, ...pendingWorldState };
    for (const k of Object.keys(pendingWorldState)) {
      delete pendingWorldState[k];
    }
    domainsDirty = true;
  }

  if (Object.keys(pendingDomainInsights).length > 0) {
    dashboard.domainInsights = {
      ...dashboard.domainInsights,
      ...pendingDomainInsights,
    };
    for (const k of Object.keys(pendingDomainInsights)) {
      delete pendingDomainInsights[k];
    }
    domainsDirty = true;
  }

  if (domainsDirty) bumpDomainsRevision();
}

function narrativesBucket(): Record<string, UiEventNarrative> {
  return batchNarratives ?? dashboard.eventNarratives;
}

function commitEventsBuffer(buf: UiEvent[]): void {
  if (batchEvents !== null) {
    batchEvents = buf;
  } else {
    dashboard.events = buf;
    eventIdToIndex.clear();
  }
}

function commitSignalsBuffer(buf: UiSignal[]): void {
  if (batchSignals !== null) batchSignals = buf;
  else dashboard.recentSignals = buf;
}

function commitCausalBuffer(buf: UiCausalEdge[]): void {
  if (batchCausalEdges !== null) batchCausalEdges = buf;
  else dashboard.recentCausalEdges = buf;
}

function commitNarrativesBucket(bucket: Record<string, UiEventNarrative>): void {
  if (batchNarratives !== null) batchNarratives = bucket;
  else dashboard.eventNarratives = bucket;
}

const pendingSeverityByDomain = new Map<string, number[]>();

function queueSeverity(event: UiEvent): void {
  if (batchDepth > 0) {
    batchSeverityEvents.push(event);
    return;
  }
  let list = pendingSeverityByDomain.get(event.domain);
  if (!list) {
    list = [];
    pendingSeverityByDomain.set(event.domain, list);
  }
  list.push(event.severity_score);
}

/** Called from `sortAndTrimDashboardBuffers` (debounced per frame). */
export function flushPendingSeverityUpdates(): void {
  if (batchSeverityEvents.length > 0) {
    const nextHist = { ...dashboard.domainSeverityHistory };
    for (const event of batchSeverityEvents) {
      let hist = nextHist[event.domain] ?? [];
      hist = hist.concat(event.severity_score);
      if (hist.length > MAX_SEVERITY_HISTORY) {
        hist = hist.slice(hist.length - MAX_SEVERITY_HISTORY);
      }
      nextHist[event.domain] = hist;
    }
    batchSeverityEvents.length = 0;
    dashboard.domainSeverityHistory = nextHist;
    return;
  }
  if (pendingSeverityByDomain.size === 0) return;
  const nextHist = { ...dashboard.domainSeverityHistory };
  for (const [domain, scores] of pendingSeverityByDomain) {
    let hist = nextHist[domain] ?? [];
    for (const score of scores) {
      hist = hist.concat(score);
      if (hist.length > MAX_SEVERITY_HISTORY) {
        hist = hist.slice(hist.length - MAX_SEVERITY_HISTORY);
      }
    }
    nextHist[domain] = hist;
  }
  pendingSeverityByDomain.clear();
  dashboard.domainSeverityHistory = nextHist;
}

function mergeEventInPlace(next: UiEvent): void {
  if (batchEvents !== null) {
    commitEventsBuffer(mergeOrAppendById(batchEvents, next, MAX_EVENTS + 64));
    return;
  }
  pendingEvents.set(next.id, next);
}

export function rebuildEventIdIndex(): void {
  eventIdToIndex.clear();
  dashboard.events.forEach((row, i) => {
    eventIdToIndex.set(row.id, i);
  });
}

// ---------------------------------------------------------------------------
// Mutation helpers (called from connection.svelte.ts row callbacks)
// ---------------------------------------------------------------------------

export function applyEvent(row: Event): void {
  let next: UiEvent;
  try {
    next = projectEvent(row);
  } catch (e) {
    console.error("openatlas: projectEvent failed, row dropped", e, row);
    const detail = e instanceof Error ? e.message : String(e);
    notifyError({
      code: NOTIFY_CODES.EVENT_PROJECT,
      title: "Could not import an event row",
      message:
        "The event was skipped so the rest of the stream stays responsive. A schema or domain mismatch may be involved.",
      detail,
      action:
        "If this was after a SpacetimeDB or client upgrade, regenerate and publish the module, then hard-refresh the app.",
      dedupeKey: `EVENT_PROJECT:${detail}`,
    });
    return;
  }
  mergeEventInPlace(next);
  queueSeverity(next);
}

export function removeEvent(id: bigint): void {
  const key = String(id);
  if (batchEvents !== null) {
    batchEvents = batchEvents.filter((row) => row.id !== key);
    return;
  }
  pendingEvents.delete(key);
  pendingEventDeletes.add(key);
}

export function applySignal(row: Signal): void {
  const next = projectSignal(row);
  if (batchSignals !== null) {
    commitSignalsBuffer(mergeOrAppendById(batchSignals, next, MAX_SIGNALS * 2));
    return;
  }
  pendingSignals.set(next.id, next);
}

export function removeSignal(id: bigint): void {
  const key = String(id);
  if (batchSignals !== null) {
    batchSignals = batchSignals.filter((row) => row.id !== key);
    return;
  }
  pendingSignals.delete(key);
  pendingSignalDeletes.add(key);
}

export function applyCausalEdge(row: CausalEdge): void {
  const next = projectCausalEdge(row);
  if (batchCausalEdges !== null) {
    commitCausalBuffer(
      mergeOrAppendById(batchCausalEdges, next, MAX_CAUSAL_EDGES * 2),
    );
    return;
  }
  pendingCausalEdges.set(next.id, next);
}

export function removeCausalEdge(id: bigint): void {
  const key = String(id);
  if (batchCausalEdges !== null) {
    batchCausalEdges = batchCausalEdges.filter((row) => row.id !== key);
    return;
  }
  pendingCausalEdges.delete(key);
  pendingCausalDeletes.add(key);
}

export function applyWorldState(row: WorldStateRow): void {
  const next = projectWorldState(row);
  if (batchDepth > 0) {
    dashboard.domainState = { ...dashboard.domainState, [next.domain]: next };
    return;
  }
  pendingWorldState[next.domain] = next;
}

export function applyDomainInsight(row: DomainInsight): void {
  const next = projectDomainInsight(row);
  if (batchDepth > 0) {
    dashboard.domainInsights = {
      ...dashboard.domainInsights,
      [next.domain]: next,
    };
    return;
  }
  pendingDomainInsights[next.domain] = next;
}

export function applyEventNarrative(row: EventNarrative): void {
  const next = projectEventNarrative(row);
  const merged: Record<string, UiEventNarrative> = {
    ...narrativesBucket(),
    [next.event_id]: next,
  };
  if (batchNarratives === null) {
    evictOldestNarratives(merged, MAX_EVENT_NARRATIVES);
  }
  commitNarrativesBucket(merged);
}

export function removeEventNarrative(eventId: bigint): void {
  const key = String(eventId);
  if (!(key in dashboard.eventNarratives)) return;
  const { [key]: _omit, ...rest } = dashboard.eventNarratives;
  dashboard.eventNarratives = rest;
}

/**
 * Keeps the narrative dictionary bounded by dropping entries with the
 * oldest `updated_at`. We prefer `updated_at` over insertion order so
 * replay reconstructs an identical cache regardless of event arrival
 * order. In-place mutation is safe because the dictionary is a fresh
 * object returned from a spread above.
 */
function evictOldestNarratives(
  bucket: Record<string, UiEventNarrative>,
  max: number,
): void {
  const keys = Object.keys(bucket);
  if (keys.length <= max) return;
  keys
    .sort(
      (a, b) =>
        Date.parse(bucket[a]!.updated_at) - Date.parse(bucket[b]!.updated_at),
    )
    .slice(0, keys.length - max)
    .forEach((key) => {
      delete bucket[key];
    });
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Insert-or-replace a row by id, cap the buffer at `max`. This is the
 * inverse of a "prepend-then-dedupe" — new rows land at the tail so
 * ordinal-ordered queries stay monotonically increasing.
 */
function mergeOrAppendById<T extends { id: string }>(
  buffer: readonly T[],
  next: T,
  max: number,
): T[] {
  const existingIdx = buffer.findIndex((row) => row.id === next.id);
  let out: T[];
  if (existingIdx >= 0) {
    out = buffer.slice();
    out[existingIdx] = next;
  } else {
    out = buffer.concat(next);
  }
  if (out.length > max) {
    out.splice(0, out.length - max);
  }
  return out;
}

