/**
 * Reactive UI state fed from SpacetimeDB row events.
 *
 * # Why project here?
 *
 * The generated SDK rows use camelCase field names and numeric domain
 * tags (matching the module schema). The rest of the UI was designed
 * around string ids and snake_case (matching an older REST envelope).
 * Translating at the edge — here — keeps components unaware of the
 * transport and keeps the SDK bindings unmodified (they are
 * regenerated by `spacetime generate`).
 *
 * # Bounds
 *
 * Each projected list has a fixed maximum size. The module *already*
 * caps the rings on the server, but we apply a second cap here so:
 *   * a browser that connects to a module with a larger ring than we
 *     expect still stays responsive; and
 *   * subscription queries like `ORDER BY ordinal DESC LIMIT N` have a
 *     canonical `N` to reference.
 *
 * The `apply*` and `remove*` helpers are the only permitted mutation
 * path — `connection.svelte.ts` calls them from SDK row callbacks.
 */

import type {
  CausalEdge,
  DomainInsight,
  Event,
  EventNarrative,
  Signal,
  WorldStateRow,
} from "./stdb/types";
import { domainIdFromTag } from "./domain";
import { notifyError } from "./notify/notify";
import { NOTIFY_CODES } from "./notify/notify-codes";
import {
  MAX_CAUSAL_EDGES,
  MAX_EVENT_NARRATIVES,
  MAX_EVENTS,
  MAX_SEVERITY_HISTORY,
  MAX_SIGNALS,
} from "./data-limits";
import type {
  ConnectionState,
  UiCausalEdge,
  UiDomainInsight,
  UiEvent,
  UiEventNarrative,
  UiPredictedDisruption,
  UiSignal,
  UiWorldState,
} from "./types";

export {
  MAX_CAUSAL_EDGES,
  MAX_EVENT_NARRATIVES,
  MAX_EVENTS,
  MAX_SEVERITY_HISTORY,
  MAX_SIGNALS,
} from "./data-limits";

/**
 * Singleton dashboard state. Exposed as a rune-backed object so
 * components deep-read fields reactively without bespoke store
 * plumbing.
 */
export const dashboard = $state({
  events: [] as UiEvent[],
  recentSignals: [] as UiSignal[],
  domainState: {} as Record<string, UiWorldState>,
  domainSeverityHistory: {} as Record<string, number[]>,
  recentCausalEdges: [] as UiCausalEdge[],
  domainInsights: {} as Record<string, UiDomainInsight>,
  /**
   * Keyed by `event_id` (string). Sparse: the server only writes
   * narratives above a severity threshold, so most events will have no
   * entry. Consumers should always default to "no narrative available".
   */
  eventNarratives: {} as Record<string, UiEventNarrative>,
  selectedDomain: null as string | null,
  connection: "connecting" as ConnectionState,
  /**
   * Last SpacetimeDB error (connect, subscription, or manual reconnect
   * hint). Cleared on successful subscription setup.
   */
  connectionLastError: null as string | null,
  /** `demo` = synthetic `demo-seed` data; `live` = SpacetimeDB projection. */
  dataMode: "live" as "live" | "demo",
});

export function setConnection(next: ConnectionState): void {
  dashboard.connection = next;
}

export function setConnectionLastError(
  message: string | null,
): void {
  dashboard.connectionLastError = message;
}

export function setSelectedDomain(next: string | null): void {
  dashboard.selectedDomain = next;
}

export function matchesSelectedDomain(candidate: string): boolean {
  const selected = dashboard.selectedDomain;
  return selected === null || selected === candidate;
}

/** All domains the UI is currently tracking, in stable alphabetical order. */
export function activeDomains(): UiWorldState[] {
  return Object.values(dashboard.domainState).sort((a, b) =>
    a.domain.localeCompare(b.domain),
  );
}

// ---------------------------------------------------------------------------
// Row projections — SDK shape → UI shape
// ---------------------------------------------------------------------------

function projectLocation(
  loc: Event["location"],
): { lat: number; lon: number } | null {
  if (loc == null) return null;
  if (typeof loc === "object" && "lat" in loc && "lon" in loc) {
    return {
      lat: (loc as { lat: number }).lat,
      lon: (loc as { lon: number }).lon,
    };
  }
  return null;
}

function projectEvent(row: Event): UiEvent {
  return {
    id: String(row.id),
    ordinal: Number(row.ordinal),
    timestamp: row.timestamp.toISOString(),
    domain: domainIdFromTag(row.domain),
    severity_score: row.severityScore,
    location: projectLocation(row.location),
  };
}

function projectSignal(row: Signal): UiSignal {
  return {
    id: String(row.id),
    event_id: String(row.eventId),
    domain: domainIdFromTag(row.domain),
    score: row.score,
    reason: row.reason,
  };
}

function projectCausalEdge(row: CausalEdge): UiCausalEdge {
  return {
    id: String(row.id),
    source_event_id: String(row.sourceEventId),
    target_event_id: String(row.targetEventId),
    influence_score: row.influenceScore,
    decay_rate: row.decayRate,
  };
}

function projectWorldState(row: WorldStateRow): UiWorldState {
  return {
    domain: domainIdFromTag(row.domain),
    event_count: Number(row.eventCount),
    avg_severity: row.avgSeverity,
    risk_index: row.riskIndex,
  };
}

function projectEventNarrative(row: EventNarrative): UiEventNarrative {
  return {
    event_id: String(row.eventId),
    headline: row.headline,
    summary: row.summary,
    inference: row.inference,
    predicted_disruption: parseDisruptions(row.predictedDisruptionJson),
    updated_at: row.updatedAt.toISOString(),
  };
}

/**
 * The module writes `predicted_disruption_json` as a JSON array of
 * `{entity, severity, note}`. We parse defensively: any malformed row
 * drops back to an empty list rather than crashing the view. This
 * preserves the "graceful fallback" contract for the Event Detail
 * view when bindings, schema, or data race each other during a deploy.
 */
function parseDisruptions(raw: string): UiPredictedDisruption[] {
  if (raw === "") return [];
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return [];
    const out: UiPredictedDisruption[] = [];
    for (const item of parsed) {
      if (
        item !== null &&
        typeof item === "object" &&
        "entity" in item &&
        "severity" in item &&
        "note" in item &&
        typeof (item as { entity: unknown }).entity === "string" &&
        typeof (item as { severity: unknown }).severity === "string" &&
        typeof (item as { note: unknown }).note === "string"
      ) {
        out.push({
          entity: (item as { entity: string }).entity,
          severity: (item as { severity: string }).severity,
          note: (item as { note: string }).note,
        });
      }
    }
    return out;
  } catch {
    return [];
  }
}

function projectDomainInsight(row: DomainInsight): UiDomainInsight {
  return {
    domain: domainIdFromTag(row.domain),
    trend: row.trend,
    anomaly_count_recent: row.anomalyCountRecent,
    dominant_source: row.dominantSource || null,
    source_link: row.sourceLink || null,
    narrative: row.narrative,
    updated_at: row.updatedAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Mutation helpers (called from connection.svelte.ts row callbacks)
// ---------------------------------------------------------------------------

export function applyEvent(row: Event): void {
  let next: UiEvent;
  try {
    next = projectEvent(row);
  } catch (e) {
    console.error("openatlas: projectEvent failed, row dropped", e, row);
    const detail = e instanceof Error ? e.message : String(e);
    notifyError({
      code: NOTIFY_CODES.EVENT_PROJECT,
      title: "Could not import an event row",
      message:
        "The event was skipped so the rest of the stream stays responsive. A schema or domain mismatch may be involved.",
      detail,
      action:
        "If this was after a SpacetimeDB or client upgrade, regenerate and publish the module, then hard-refresh the app.",
      dedupeKey: `EVENT_PROJECT:${detail}`,
    });
    return;
  }
  const merged = mergeOrAppendById(dashboard.events, next, MAX_EVENTS);
  dashboard.events = merged;
  recordSeverity(next);
}

export function removeEvent(id: bigint): void {
  const key = String(id);
  dashboard.events = dashboard.events.filter((row) => row.id !== key);
}

export function applySignal(row: Signal): void {
  const next = projectSignal(row);
  dashboard.recentSignals = mergeOrAppendById(
    dashboard.recentSignals,
    next,
    MAX_SIGNALS,
  );
}

export function removeSignal(id: bigint): void {
  const key = String(id);
  dashboard.recentSignals = dashboard.recentSignals.filter(
    (row) => row.id !== key,
  );
}

export function applyCausalEdge(row: CausalEdge): void {
  const next = projectCausalEdge(row);
  dashboard.recentCausalEdges = mergeOrAppendById(
    dashboard.recentCausalEdges,
    next,
    MAX_CAUSAL_EDGES,
  );
}

export function removeCausalEdge(id: bigint): void {
  const key = String(id);
  dashboard.recentCausalEdges = dashboard.recentCausalEdges.filter(
    (row) => row.id !== key,
  );
}

export function applyWorldState(row: WorldStateRow): void {
  const next = projectWorldState(row);
  dashboard.domainState = { ...dashboard.domainState, [next.domain]: next };
}

export function applyDomainInsight(row: DomainInsight): void {
  const next = projectDomainInsight(row);
  dashboard.domainInsights = {
    ...dashboard.domainInsights,
    [next.domain]: next,
  };
}

export function applyEventNarrative(row: EventNarrative): void {
  const next = projectEventNarrative(row);
  const merged: Record<string, UiEventNarrative> = {
    ...dashboard.eventNarratives,
    [next.event_id]: next,
  };
  evictOldestNarratives(merged, MAX_EVENT_NARRATIVES);
  dashboard.eventNarratives = merged;
}

export function removeEventNarrative(eventId: bigint): void {
  const key = String(eventId);
  if (!(key in dashboard.eventNarratives)) return;
  const { [key]: _omit, ...rest } = dashboard.eventNarratives;
  dashboard.eventNarratives = rest;
}

/**
 * Keeps the narrative dictionary bounded by dropping entries with the
 * oldest `updated_at`. We prefer `updated_at` over insertion order so
 * replay reconstructs an identical cache regardless of event arrival
 * order. In-place mutation is safe because the dictionary is a fresh
 * object returned from a spread above.
 */
function evictOldestNarratives(
  bucket: Record<string, UiEventNarrative>,
  max: number,
): void {
  const keys = Object.keys(bucket);
  if (keys.length <= max) return;
  keys
    .sort(
      (a, b) =>
        Date.parse(bucket[a]!.updated_at) - Date.parse(bucket[b]!.updated_at),
    )
    .slice(0, keys.length - max)
    .forEach((key) => {
      delete bucket[key];
    });
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Insert-or-replace a row by id, cap the buffer at `max`. This is the
 * inverse of a "prepend-then-dedupe" — new rows land at the tail so
 * ordinal-ordered queries stay monotonically increasing.
 */
function mergeOrAppendById<T extends { id: string }>(
  buffer: readonly T[],
  next: T,
  max: number,
): T[] {
  const existingIdx = buffer.findIndex((row) => row.id === next.id);
  let out: T[];
  if (existingIdx >= 0) {
    out = buffer.slice();
    out[existingIdx] = next;
  } else {
    out = buffer.concat(next);
  }
  if (out.length > max) {
    out.splice(0, out.length - max);
  }
  return out;
}

function recordSeverity(event: UiEvent): void {
  const existing = dashboard.domainSeverityHistory[event.domain] ?? [];
  const nextHistory = existing.concat(event.severity_score);
  if (nextHistory.length > MAX_SEVERITY_HISTORY) {
    nextHistory.splice(0, nextHistory.length - MAX_SEVERITY_HISTORY);
  }
  dashboard.domainSeverityHistory = {
    ...dashboard.domainSeverityHistory,
    [event.domain]: nextHistory,
  };
}
