/** Stable codes for toasts, logs, and support — keep short and SCREAMING_SNAKE. */
export const NOTIFY_CODES = {
  STDB_LIVE: "STDB_LIVE",
  STDB_OFFLINE: "STDB_OFFLINE",
  STDB_RECONNECTING: "STDB_RECONNECTING",
  STDB_CONNECT_FAIL: "STDB_CONNECT_FAIL",
  STDB_SUBSCRIPTION: "STDB_SUBSCRIPTION",
  STDB_BUILD: "STDB_BUILD",
  INGEST_UNREACHABLE: "INGEST_UNREACHABLE",
  LLM_UNREACHABLE: "LLM_UNREACHABLE",
  EVENT_PROJECT: "EVENT_PROJECT",
  DOMAIN_CATALOG: "DOMAIN_CATALOG",
} as const;

export type NotifyCode = (typeof NOTIFY_CODES)[keyof typeof NOTIFY_CODES];
