// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IngestEventReducer from "../ingest_event_reducer";
import LinkCausalEventsReducer from "../link_causal_events_reducer";

export type IngestEventParams = __Infer<typeof IngestEventReducer>;
export type LinkCausalEventsParams = __Infer<typeof LinkCausalEventsReducer>;

