<!--
  Executive Summary Hub — the landing page of OpenAtlas.

  Daily briefing is generated by Ollama via openatlas-llm-bridge from live telemetry.
-->
<script lang="ts">
  import { Download, FileText, Sparkles } from "@lucide/svelte";

  import { useNarrativeSubscription } from "../narrative-subscription";
  import { dashboard } from "../state.svelte";

  useNarrativeSubscription();
  import { buildHubTiles, computeThreatIndex } from "../hub";
  import { llmSnapshotCounts } from "../llm-snapshot";
  import { buildDeterministicBriefing } from "../briefing-fallback";
  import {
    DAILY_BRIEFING_PROMPT,
    llmBlockedReason,
    llmCanRun,
    llmSnapshotFromDashboard,
    runDashboardLlm,
  } from "../llm-analysis";
  import { ensureLlmReady, readiness, refreshRemoteReadiness } from "../readiness.svelte";
  import BriefingMarkdown from "../components/BriefingMarkdown.svelte";
  import { NumericIndexBadge } from "../primitives";
  import { META_ICONS } from "../domain-icons";
  import { domainLabel } from "../colors";
  import { navigate } from "../router.svelte";

  import CompactNumber from "../components/CompactNumber.svelte";
  import HubTile from "./HubTile.svelte";
  import HubOverviewCharts from "./HubOverviewCharts.svelte";
  import DataPipelineBanner from "../components/DataPipelineBanner.svelte";

  const tiles = $derived(
    buildHubTiles(
      dashboard.domainState,
      dashboard.domainInsights,
      dashboard.recentSignals,
    ),
  );

  const threatIndex = $derived(computeThreatIndex(dashboard.domainState));

  // The threat index tone scales alongside its value — the severity
  // bucket boundaries mirror `bucketRisk` so visual language stays
  // consistent across the hub and the tiles.
  const threatTone = $derived<"neutral" | "warn" | "danger">(
    threatIndex >= 7 ? "danger" : threatIndex >= 4 ? "warn" : "neutral",
  );

  let briefingOpen = $state(false);
  let briefingLoading = $state(false);
  let briefingError = $state<string | null>(null);
  let briefingLlmText = $state<string | null>(null);
  let briefingModel = $state<string | null>(null);
  let briefingUserFocus = $state("");
  let briefingUsedFallback = $state(false);

  const llmCtx = $derived({
    dataMode: dashboard.dataMode,
    connection: dashboard.connection,
    snapshot: llmSnapshotFromDashboard({
      events: dashboard.events,
      recentSignals: dashboard.recentSignals,
      domainState: dashboard.domainState,
      domainInsights: dashboard.domainInsights,
      recentCausalEdges: dashboard.recentCausalEdges,
      eventNarratives: dashboard.eventNarratives,
    }),
  });

  const llmCounts = $derived(llmSnapshotCounts(llmCtx.snapshot));

  const blockedReason = $derived(
    llmBlockedReason(llmCtx, readiness.llmReady),
  );

  const briefingSource = $derived(
    briefingLoading
      ? "Generating with Ollama…"
      : briefingLlmText && !briefingUsedFallback
        ? `Ollama${briefingModel ? ` (${briefingModel})` : ""}`
        : briefingUsedFallback
          ? "Template (LLM unavailable)"
          : briefingError
            ? "LLM unavailable"
            : "Not generated yet",
  );

  const briefingDisplay = $derived(
    briefingLlmText ??
      (briefingUsedFallback
        ? buildDeterministicBriefing(llmCtx.snapshot)
        : null),
  );

  $effect(() => {
    if (briefingOpen) void refreshRemoteReadiness();
  });

  function toggleBriefing(): void {
    const opening = !briefingOpen;
    briefingOpen = opening;
    if (opening) void generateBriefing(false);
  }

  async function generateBriefing(force: boolean): Promise<void> {
    if (!force && briefingLlmText && !briefingError) return;
    briefingError = null;
    briefingLoading = true;
    briefingUsedFallback = false;

    try {
      await refreshRemoteReadiness();
      await ensureLlmReady(false);

      if (!llmCanRun(llmCtx, readiness.llmReady)) {
        briefingUsedFallback = true;
        briefingLlmText = buildDeterministicBriefing(llmCtx.snapshot);
        briefingModel = null;
        briefingError =
          llmBlockedReason(llmCtx, readiness.llmReady) ??
          "LLM is not ready — showing template briefing.";
        return;
      }

      const focus = briefingUserFocus.trim();
      const prompt = focus
        ? `${DAILY_BRIEFING_PROMPT}\n\nOPERATOR_FOCUS: ${focus}`
        : DAILY_BRIEFING_PROMPT;
      const r = await runDashboardLlm(llmCtx, prompt);
      briefingLlmText = r.text.trim();
      briefingModel = r.model;
      if (!briefingLlmText) {
        briefingUsedFallback = true;
        briefingLlmText = buildDeterministicBriefing(llmCtx.snapshot);
        briefingError = "Ollama returned an empty response — showing template briefing.";
      }
    } catch (e) {
      briefingUsedFallback = true;
      briefingLlmText = buildDeterministicBriefing(llmCtx.snapshot);
      briefingModel = null;
      briefingError = e instanceof Error ? e.message : String(e);
    } finally {
      briefingLoading = false;
    }
  }

  function downloadBriefing(): void {
    const body =
      briefingDisplay?.trim() ??
      briefingError ??
      "No briefing generated yet.";
    const blob = new Blob([body], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = "openatlas-briefing.md";
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
  }
</script>

<section class="hub">
  <header class="hub-header">
    <div class="hub-headline">
      <div class="hub-kicker">
        Global AI Inference Engine · Central Command
      </div>
      <h1 class="hub-title">
        <META_ICONS.radar size={22} strokeWidth={1.75} />
        <span>Executive Summary Hub</span>
      </h1>
      <p class="hub-subtitle">
        Cross-domain macroscopic analysis of {tiles.length} tracked
        domains. Tiles ordered by live risk index. Click any tile to
        drill into its matrix.
      </p>
    </div>

    <div class="hub-actions">
      <NumericIndexBadge
        label="Global Threat Index"
        value={threatIndex.toFixed(1)}
        denominator={10}
        tone={threatTone}
      />
      <button
        type="button"
        class="hub-btn is-primary"
        onclick={toggleBriefing}
        aria-pressed={briefingOpen}
        disabled={briefingLoading}
      >
        <FileText size={14} strokeWidth={1.75} />
        <span>{briefingLoading ? "Generating…" : "Generate Daily Briefing"}</span>
      </button>
    </div>
  </header>

  <DataPipelineBanner />

  <HubOverviewCharts />

  <div class="hub-grid">
    {#each tiles as tile (tile.id)}
      <HubTile {tile} />
    {/each}
  </div>

  {#if briefingOpen}
    <aside class="hub-briefing" aria-label="Daily briefing" aria-busy={briefingLoading}>
      <div class="hub-briefing-head">
        <div>
          <h2>Daily Briefing</h2>
          <p class="hub-briefing-meta">
            {briefingSource} · <CompactNumber value={llmCounts.events} /> events · {llmCounts.domains}
            domains · {llmCounts.insights} insights
          </p>
        </div>
        <div class="hub-briefing-actions">
          <button
            type="button"
            class="hub-btn"
            onclick={() => void generateBriefing(true)}
            disabled={briefingLoading}
            title={blockedReason ?? "Regenerate with Ollama"}
          >
            <Sparkles size={14} strokeWidth={1.75} />
            <span>Regenerate</span>
          </button>
          <button
            type="button"
            class="hub-btn"
            onclick={downloadBriefing}
            aria-label="Download briefing as markdown"
          >
            <Download size={14} strokeWidth={1.75} />
            <span>Download .md</span>
          </button>
        </div>
      </div>
      <label class="hub-briefing-label" for="briefing-focus"
        >Optional focus for the model</label
      >
      <textarea
        id="briefing-focus"
        class="hub-briefing-textarea"
        rows={2}
        bind:value={briefingUserFocus}
        placeholder="e.g. energy–transport coupling, cyber anomalies in the last hour"
        disabled={briefingLoading}
      ></textarea>
      {#if briefingError}
        <div class="hub-briefing-error" role="alert">
          <p>{briefingError}</p>
          <button
            type="button"
            class="hub-briefing-link"
            onclick={() => navigate("/settings")}>Open Settings → LLM</button
          >
        </div>
      {/if}
      {#if briefingLoading}
        <p class="hub-briefing-wait">
          Calling Ollama via the LLM bridge… This can take 30–90 seconds on CPU.
        </p>
      {:else if briefingDisplay}
        <BriefingMarkdown source={briefingDisplay} />
      {:else if !briefingError}
        <p class="hub-briefing-wait">Click Regenerate to run the briefing with Ollama.</p>
      {/if}
      <footer class="hub-briefing-foot">
        {#if briefingDisplay && !briefingUsedFallback}
          Generated from live telemetry via Ollama. Regenerate after ingest
          updates the dashboard.
        {:else if briefingUsedFallback}
          Template briefing from live telemetry. Fix LLM in Settings, then Regenerate.
        {:else}
          Requires Live SpacetimeDB data, <code>ollama serve</code>, and
          <code>./dev.sh llm:start</code> (or full stack Run).
        {/if}
      </footer>
    </aside>
  {/if}


  {#if tiles.length === 0}
    <div class="hub-empty">
      <span>Waiting for the first event ring…</span>
      <small>The hub populates as soon as {domainLabel("energy")} and peers report in.</small>
    </div>
  {/if}
</section>

<style>
  .hub {
    max-width: 1560px;
    margin: 0 auto;
    padding: var(--space-6) var(--space-5) var(--space-10);
    display: flex;
    flex-direction: column;
    gap: var(--space-6);
  }

  .hub-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: var(--space-5);
    flex-wrap: wrap;
  }

  .hub-kicker {
    font-family: var(--font-mono);
    font-size: 10px;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: var(--accent);
    margin-bottom: var(--space-2);
  }
  .hub-title {
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    font-size: 22px;
    font-weight: 600;
    letter-spacing: -0.01em;
    color: var(--text-1);
  }
  .hub-title :global(svg) {
    color: var(--sev-high);
  }
  .hub-subtitle {
    margin-top: var(--space-2);
    color: var(--text-2);
    max-width: 64ch;
  }

  .hub-actions {
    display: inline-flex;
    align-items: center;
    gap: var(--space-3);
    flex-wrap: wrap;
  }

  .hub-btn {
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    padding: 7px 12px;
    border-radius: var(--radius);
    background: var(--bg-2);
    color: var(--text-1);
    border: 1px solid var(--border-1);
    font-size: 12px;
    font-weight: 500;
    cursor: pointer;
    transition:
      background var(--motion-fast) var(--ease),
      border-color var(--motion-fast) var(--ease);
  }
  .hub-btn:hover {
    background: var(--bg-3);
    border-color: var(--border-2);
  }
  .hub-btn.is-primary {
    background: linear-gradient(
      135deg,
      var(--accent) 0%,
      var(--accent-violet) 100%
    );
    color: #0b0b0f;
    border-color: transparent;
    font-weight: 600;
  }
  .hub-btn.is-primary:hover {
    filter: brightness(1.05);
  }
  .hub-grid {
    display: grid;
    grid-template-columns: repeat(4, minmax(0, 1fr));
    gap: var(--space-3);
  }

  .hub-briefing {
    background: var(--bg-1);
    border: 1px solid var(--border-1);
    border-radius: var(--radius-lg);
    padding: var(--space-5);
    display: flex;
    flex-direction: column;
    gap: var(--space-3);
  }
  .hub-briefing-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-3);
  }
  .hub-briefing-head h2 {
    font-size: 14px;
    letter-spacing: 0.02em;
    color: var(--text-1);
  }
  .hub-briefing-wait {
    margin: 0;
    font-size: 12px;
    line-height: 1.5;
    color: var(--text-2);
    padding: var(--space-3) var(--space-4);
    background: var(--bg-2);
    border: 1px solid var(--border-1);
    border-radius: var(--radius);
  }
  .hub-briefing-foot {
    font-size: 11px;
    color: var(--text-3);
  }
  .hub-briefing-meta {
    margin: 4px 0 0;
    font-size: 11px;
    color: var(--text-3);
  }
  .hub-briefing-actions {
    display: inline-flex;
    gap: var(--space-2);
    flex-shrink: 0;
  }
  .hub-briefing-label {
    font-size: 11px;
    color: var(--text-2);
  }
  .hub-briefing-textarea {
    width: 100%;
    box-sizing: border-box;
    font-family: var(--font-sans, inherit);
    font-size: 12px;
    line-height: 1.4;
    padding: var(--space-3);
    border-radius: var(--radius);
    border: 1px solid var(--border-1);
    background: var(--bg-2);
    color: var(--text-1);
    resize: vertical;
    min-height: 3rem;
  }
  .hub-briefing-textarea:disabled {
    opacity: 0.6;
  }
  .hub-briefing-error {
    font-size: 12px;
    color: var(--sev-high);
    padding: var(--space-2) var(--space-3);
    border-radius: var(--radius);
    border: 1px solid color-mix(in srgb, var(--sev-high) 40%, var(--border-1));
    background: color-mix(in srgb, var(--sev-high) 8%, var(--bg-2));
  }
  .hub-briefing-error p {
    margin: 0 0 var(--space-2);
    line-height: 1.45;
  }
  .hub-briefing-link {
    font: inherit;
    font-size: 11px;
    padding: 0;
    border: 0;
    background: none;
    color: var(--accent);
    text-decoration: underline;
    cursor: pointer;
  }
  .hub-empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: var(--space-2);
    padding: var(--space-10);
    border: 1px dashed var(--border-2);
    border-radius: var(--radius-lg);
    color: var(--text-2);
  }
  .hub-empty small {
    color: var(--text-3);
  }

  @media (max-width: 1200px) {
    .hub-grid {
      grid-template-columns: repeat(3, minmax(0, 1fr));
    }
  }
  @media (max-width: 800px) {
    .hub-grid {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
  }
  @media (max-width: 520px) {
    .hub-grid {
      grid-template-columns: minmax(0, 1fr);
    }
    .hub-header {
      flex-direction: column;
    }
  }
</style>
