// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sourceEventId: __t.u64().name("source_event_id"),
  targetEventId: __t.u64().name("target_event_id"),
  influenceScore: __t.f64().name("influence_score"),
  decayRate: __t.f64().name("decay_rate"),
  createdAt: __t.timestamp().name("created_at"),
});
