// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Location,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  timestamp: __t.timestamp(),
  domain: __t.u8(),
  severityScore: __t.f64().name("severity_score"),
  get location() {
    return __t.option(Location);
  },
  payloadJson: __t.string().name("payload_json"),
  ordinal: __t.u64(),
});
