// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

import IngestEventReducer from "./ingest_event_reducer";
import LinkCausalEventsReducer from "./link_causal_events_reducer";

import CausalEdgeRow from "./causal_edge_table";
import DomainInsightRow from "./domain_insight_table";
import EventRow from "./event_table";
import EventNarrativeRow from "./event_narrative_table";
import SignalRow from "./signal_table";
import WorldStateRow from "./world_state_table";




const tablesSchema = __schema({
  causal_edge: __table({
    name: 'causal_edge',
    indexes: [
      { accessor: 'id', name: 'causal_edge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'causal_edge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CausalEdgeRow),
  domain_insight: __table({
    name: 'domain_insight',
    indexes: [
      { accessor: 'domain', name: 'domain_insight_domain_idx_btree', algorithm: 'btree', columns: [
        'domain',
      ] },
    ],
    constraints: [
      { name: 'domain_insight_domain_key', constraint: 'unique', columns: ['domain'] },
    ],
  }, DomainInsightRow),
  event: __table({
    name: 'event',
    indexes: [
      { accessor: 'id', name: 'event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventRow),
  event_narrative: __table({
    name: 'event_narrative',
    indexes: [
      { accessor: 'event_id', name: 'event_narrative_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
    ],
    constraints: [
      { name: 'event_narrative_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, EventNarrativeRow),
  signal: __table({
    name: 'signal',
    indexes: [
      { accessor: 'id', name: 'signal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'signal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SignalRow),
  world_state: __table({
    name: 'world_state',
    indexes: [
      { accessor: 'domain', name: 'world_state_domain_idx_btree', algorithm: 'btree', columns: [
        'domain',
      ] },
    ],
    constraints: [
      { name: 'world_state_domain_key', constraint: 'unique', columns: ['domain'] },
    ],
  }, WorldStateRow),
});


const reducersSchema = __reducers(
  __reducerSchema("ingest_event", IngestEventReducer),
  __reducerSchema("link_causal_events", LinkCausalEventsReducer),
);


const proceduresSchema = __procedures(
);


const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;


export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);


export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);


export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;

export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;

export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;

export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;

export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;


export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}


export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}


export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {

  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };


  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

