// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CausalEdge = __t.object("CausalEdge", {
  id: __t.u64(),
  sourceEventId: __t.u64(),
  targetEventId: __t.u64(),
  influenceScore: __t.f64(),
  decayRate: __t.f64(),
  createdAt: __t.timestamp(),
});
export type CausalEdge = __Infer<typeof CausalEdge>;

export const DomainInsight = __t.object("DomainInsight", {
  domain: __t.u8(),
  trend: __t.string(),
  anomalyCountRecent: __t.u32(),
  dominantSource: __t.string(),
  sourceLink: __t.string(),
  narrative: __t.string(),
  updatedAt: __t.timestamp(),
});
export type DomainInsight = __Infer<typeof DomainInsight>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  timestamp: __t.timestamp(),
  domain: __t.u8(),
  severityScore: __t.f64(),
  get location() {
    return __t.option(Location);
  },
  payloadJson: __t.string(),
  ordinal: __t.u64(),
});
export type Event = __Infer<typeof Event>;

export const EventNarrative = __t.object("EventNarrative", {
  eventId: __t.u64(),
  headline: __t.string(),
  summary: __t.string(),
  inference: __t.string(),
  predictedDisruptionJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type EventNarrative = __Infer<typeof EventNarrative>;

export const LastEventInDomain = __t.object("LastEventInDomain", {
  domain: __t.u8(),
  eventId: __t.u64(),
  ordinal: __t.u64(),
});
export type LastEventInDomain = __Infer<typeof LastEventInDomain>;

export const Location = __t.object("Location", {
  lat: __t.f64(),
  lon: __t.f64(),
  regionTags: __t.array(__t.string()),
});
export type Location = __Infer<typeof Location>;

export const OrdinalCounter = __t.object("OrdinalCounter", {
  id: __t.u8(),
  value: __t.u64(),
});
export type OrdinalCounter = __Infer<typeof OrdinalCounter>;

export const Signal = __t.object("Signal", {
  id: __t.u64(),
  eventId: __t.u64(),
  domain: __t.u8(),
  score: __t.f64(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type Signal = __Infer<typeof Signal>;

export const WorldStateRow = __t.object("WorldStateRow", {
  domain: __t.u8(),
  eventCount: __t.u64(),
  avgSeverity: __t.f64(),
  riskIndex: __t.f64(),
  lastUpdated: __t.timestamp(),
  totalSeverity: __t.f64(),
});
export type WorldStateRow = __Infer<typeof WorldStateRow>;

