// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  domain: __t.u8().primaryKey(),
  eventCount: __t.u64().name("event_count"),
  avgSeverity: __t.f64().name("avg_severity"),
  riskIndex: __t.f64().name("risk_index"),
  lastUpdated: __t.timestamp().name("last_updated"),
  totalSeverity: __t.f64().name("total_severity"),
});
