#!/usr/bin/env bash
# Write web/.env.local for Capacitor builds (emulator / LAN device / Maincloud).
# Sourced by dev.sh — do not assume style_* helpers exist when run standalone.
set -euo pipefail

MOBILE_ENV_REPO_ROOT="${MOBILE_ENV_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
MOBILE_ENV_WEB="${MOBILE_ENV_WEB:-${MOBILE_ENV_REPO_ROOT}/web}"
# Capacitor/APK only — never clobber web/.env.local (Vite dev uses proxy + optional STDB override).
MOBILE_ENV_DEST="${MOBILE_ENV_WEB}/.env.capacitor.local"

: "${STDB_CLOUD_WS:=wss://maincloud.spacetimedb.com}"
: "${STDB_CLOUD_DB:=openatlas}"
: "${OPENATLAS_MOBILE_TARGET:=}"

_mobile_env_log() { printf '%s\n' "$*"; }

# emulator | device | none (no adb / no connected device)
mobile_detect_adb_target() {
  if ! command -v adb >/dev/null 2>&1; then
    printf 'none'
    return 0
  fi
  local serial
  serial="$(adb devices 2>/dev/null | awk 'NR>1 && $2=="device" { print $1; exit }')"
  if [[ -z "$serial" ]]; then
    printf 'none'
    return 0
  fi
  if [[ "$serial" == emulator-* ]]; then
    printf 'emulator'
    return 0
  fi
  printf 'device'
}

mobile_lan_ip() {
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") { print $(i+1); exit }}')"
  fi
  if [[ -z "$ip" ]] && command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  [[ -n "$ip" ]] || ip="192.168.1.1"
  printf '%s' "$ip"
}

mobile_resolve_target() {
  local explicit="${OPENATLAS_MOBILE_TARGET:-}"
  case "${OPENATLAS_MOBILE_STDB:-}" in
    cloud|maincloud) explicit="maincloud" ;;
  esac
  if [[ -n "$explicit" ]]; then
    printf '%s' "$explicit"
    return 0
  fi
  case "$(mobile_detect_adb_target)" in
    device) printf 'device' ;;
    emulator) printf 'emulator' ;;
    *) printf 'emulator' ;;
  esac
}

# Returns 0 when web/.env.local was written by this script (breaks Vite dev proxy).
web_env_local_is_mobile_generated() {
  local f="${MOBILE_ENV_WEB}/.env.local"
  [[ -f "$f" ]] && grep -q 'Generated by scripts/mobile-env.sh' "$f" 2>/dev/null
}

# Remove stale mobile APK env from web/.env.local so `bun run dev` uses the ingest proxy again.
web_env_local_strip_mobile() {
  if web_env_local_is_mobile_generated; then
    rm -f "${MOBILE_ENV_WEB}/.env.local"
    _mobile_env_log "removed stale web/.env.local (mobile env belongs in .env.capacitor.local)"
    return 0
  fi
  return 1
}

mobile_write_env_local() {
  local target host
  target="$(mobile_resolve_target)"
  mkdir -p "$(dirname "$MOBILE_ENV_DEST")"

  if [[ -f "$MOBILE_ENV_DEST" ]]; then
    cp -f "$MOBILE_ENV_DEST" "${MOBILE_ENV_DEST}.bak.$(date +%s)" 2>/dev/null || true
  fi
  web_env_local_strip_mobile || true

  case "$target" in
    maincloud-lan|maincloud+lan|phone-maincloud)
      host="$(mobile_lan_ip)"
      cat >"$MOBILE_ENV_DEST" <<EOF
# Generated by scripts/mobile-env.sh — Maincloud STDB + dev machine ingest/LLM on Wi‑Fi (${host})
VITE_STDB_URI=${STDB_CLOUD_WS}
VITE_STDB_DB=${STDB_CLOUD_DB}
VITE_INGEST_BASE=http://${host}:8080
VITE_LLM_BASE=http://${host}:3847
VITE_NATIVE_DEFAULT_LLM=gemini
EOF
      _mobile_env_log "mobile env: Maincloud STDB + LAN ingest/LLM at ${host}"
      _mobile_env_log "  start backend: OPENATLAS_INGEST_LAN_BIND=1 ./dev.sh start:cloud:hybrid"
      ;;
    maincloud|cloud)
      if [[ -n "${OPENATLAS_PUBLIC_INGEST_URL:-}" ]]; then
        cat >"$MOBILE_ENV_DEST" <<EOF
# Generated by scripts/mobile-env.sh — Maincloud STDB + public ingest (${OPENATLAS_PUBLIC_INGEST_URL})
VITE_STDB_URI=${STDB_CLOUD_WS}
VITE_STDB_DB=${STDB_CLOUD_DB}
VITE_INGEST_BASE=${OPENATLAS_PUBLIC_INGEST_URL}
EOF
        if [[ -n "${OPENATLAS_PUBLIC_LLM_URL:-}" ]]; then
          printf 'VITE_LLM_BASE=%s\n' "${OPENATLAS_PUBLIC_LLM_URL}" >>"$MOBILE_ENV_DEST"
        fi
        _mobile_env_log "mobile env: Maincloud + public ingest at ${OPENATLAS_PUBLIC_INGEST_URL}"
      # Hybrid ingest/LLM only when an emulator is actually connected (not CI / phone builds).
      elif [[ "$(mobile_detect_adb_target)" == "emulator" ]] \
        && [[ "${OPENATLAS_MOBILE_MAINCLOUD_PHYSICAL:-0}" != "1" ]]; then
        cat >"$MOBILE_ENV_DEST" <<EOF
# Generated by scripts/mobile-env.sh — Maincloud STDB + host ingest/LLM via emulator gateway
VITE_STDB_URI=${STDB_CLOUD_WS}
VITE_STDB_DB=${STDB_CLOUD_DB}
VITE_INGEST_BASE=http://10.0.2.2:8080
VITE_LLM_BASE=http://10.0.2.2:3847
EOF
        _mobile_env_log "mobile env: Maincloud STDB + local ingest/LLM at 10.0.2.2 (start ingest pointed at Maincloud)"
      else
        cat >"$MOBILE_ENV_DEST" <<EOF
# Generated by scripts/mobile-env.sh — Maincloud (physical device / cloud demo)
VITE_STDB_URI=${STDB_CLOUD_WS}
VITE_STDB_DB=${STDB_CLOUD_DB}
# Native APK defaults LLM provider to Gemini (API key in Settings)
VITE_NATIVE_DEFAULT_LLM=gemini
EOF
        _mobile_env_log "mobile env: Maincloud STDB only (${STDB_CLOUD_WS})"
      fi
      ;;
    device|lan|physical)
      host="$(mobile_lan_ip)"
      cat >"$MOBILE_ENV_DEST" <<EOF
# Generated by scripts/mobile-env.sh — physical device → dev machine on LAN (${host})
VITE_STDB_URI=ws://${host}:3000
VITE_STDB_DB=${STDB_CLOUD_DB}
VITE_INGEST_BASE=http://${host}:8080
VITE_LLM_BASE=http://${host}:3847
EOF
      _mobile_env_log "mobile env: LAN device → ${host} (STDB :3000, ingest :8080, LLM :3847)"
      ;;
    emulator|*)
      cat >"$MOBILE_ENV_DEST" <<EOF
# Generated by scripts/mobile-env.sh — Android emulator → host via 10.0.2.2
VITE_STDB_URI=ws://10.0.2.2:3000
VITE_STDB_DB=${STDB_CLOUD_DB}
VITE_INGEST_BASE=http://10.0.2.2:8080
VITE_LLM_BASE=http://10.0.2.2:3847
EOF
      _mobile_env_log "mobile env: emulator → 10.0.2.2 (local ./dev.sh stack)"
      ;;
  esac
  if [[ -n "${OPENATLAS_APP_VERSION:-}" ]]; then
    printf 'VITE_APP_VERSION=%s\n' "${OPENATLAS_APP_VERSION}" >>"$MOBILE_ENV_DEST"
  fi
}

mobile_write_capacitor_env() {
  mobile_write_env_local
}
